// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8K7nIVu15gz2E00jESRBfMvSOSS9jaRA',
    appId: '1:41132166430:web:8e1fa55b818d1e4b844d0f',
    messagingSenderId: '41132166430',
    projectId: 'fire-try-99d2d',
    authDomain: 'fire-try-99d2d.firebaseapp.com',
    storageBucket: 'fire-try-99d2d.appspot.com',
    measurementId: 'G-PTJHCTDQJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDduzOEHAG86NNqxPeqWIfmnVcFNffs_ug',
    appId: '1:41132166430:android:5e61791415b16dbd844d0f',
    messagingSenderId: '41132166430',
    projectId: 'fire-try-99d2d',
    storageBucket: 'fire-try-99d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3frAknr58vH7_Yr-3D7Xrk-6l1lrFdF0',
    appId: '1:41132166430:ios:ce551878b15f6421844d0f',
    messagingSenderId: '41132166430',
    projectId: 'fire-try-99d2d',
    storageBucket: 'fire-try-99d2d.appspot.com',
    iosBundleId: 'com.example.basics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3frAknr58vH7_Yr-3D7Xrk-6l1lrFdF0',
    appId: '1:41132166430:ios:ce551878b15f6421844d0f',
    messagingSenderId: '41132166430',
    projectId: 'fire-try-99d2d',
    storageBucket: 'fire-try-99d2d.appspot.com',
    iosBundleId: 'com.example.basics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8K7nIVu15gz2E00jESRBfMvSOSS9jaRA',
    appId: '1:41132166430:web:d9c6eb62239eec9e844d0f',
    messagingSenderId: '41132166430',
    projectId: 'fire-try-99d2d',
    authDomain: 'fire-try-99d2d.firebaseapp.com',
    storageBucket: 'fire-try-99d2d.appspot.com',
    measurementId: 'G-0Q2K8J2WC1',
  );
}
